In [7]:
import numpy as np
from sklearn.decomposition import NMF

X = np.array([[1, 1], [1, 2.5], [3.5, 6], [4, 1], [8, 9], [5.55, 6.7]])


In [8]:
model = NMF(n_components=2,init='random',random_state = 0)


The code creates an instance of the Non-Negative Matrix Factorization (NMF) model with the following settings:

1. Number of components: 2 (n_components=2)
2. Initialization method: Random (init='random')
3. Random seed for reproducibility: 0 (random_state=0)

This NMF model is commonly used for decomposing input data into two non-negative matrices, aiming for dimensionality reduction or feature extraction.

In [9]:
W = model.fit_transform(X)
H = model.components_


In [20]:
print("W matrix :")
print(W)
print("\nH matrix :")
print(H)
print("\nW x H Matrix :")
print(np.dot(W,H))
print("\nInitial X matrix :")
print(X)

W matrix :
[[0.43534525 0.20160064]
 [0.2021956  0.60519948]
 [1.13512562 1.37826697]
 [2.20661127 0.        ]
 [3.32732889 1.88187098]
 [2.23741806 1.42830931]]

H matrix :
[[1.81249187 0.45409485]
 [1.04651739 3.97948705]]

W x H Matrix :
[[1.0000383  0.99995515]
 [0.99982966 2.50019948]
 [3.4997863  6.00025025]
 [3.999465   1.00201081]
 [8.00016728 8.99980411]
 [5.55005259 6.69993842]]

Initial X matrix :
[[1.   1.  ]
 [1.   2.5 ]
 [3.5  6.  ]
 [4.   1.  ]
 [8.   9.  ]
 [5.55 6.7 ]]
